### ISSUE TITLE
Windows Defender Antivirus Alert

### ISSUE THREAD

**Issue by wangsu** [sgriffin53/ravenopeningsexplorer#1]
Program:Win32/Wacapew.C!ml
This program has potentially unwanted behavior.
Raven-Openings-Explorer.exe

**Comment by sgriffin53** [comment]
Hi,

Thanks for flagging this up. Apparently amateur software gets flagged by antiviruses a lot since it's not digitally signed. I don't think there's much I can do short of paying for a certificate.

The exe should be fine to run but if you don't trust the exe, you can download the repository and run the python script directly (note, you'll have to copy the /chessopeningtheory/ folder over to get it to work).

Thanks.
